### ISSUE TITLE
Minor typo in README.md

### ISSUE THREAD

**Issue by jkshenton** [RedPointyJackson/Brooglie#4]
Thanks for sharing this nice solver! I've just been playing around with and noticed that the 1D QHO potential is defined as `V(x) = 0.5*m*ω*x^2` in the README.md. I think it should be `V(x) = 0.5*m*ω^2*x^2`. 

It's a very minor issue, but since I copy-pasted this example and got confused by the 'wrong' results, I thought I'd mention it. 

Cheers.

**Comment by RedPointyJackson** [comment]
Hi,

you are totally right, I was lucky because of ω being 1. Correcting the readme.

Thanks a lot for the correction!
