### ISSUE TITLE
Julia version 1.0.5 wants the LinearAlgebra package

### ISSUE THREAD

**Issue by jkshenton** [RedPointyJackson/Brooglie#5]
Hi,

We ran into some issues when Arpack runs out of iterations and Brooglie wants to raise an ARPACKException when using julia v 1.0.5. This seems to be fixed if we include an `using LinearAlgebra`  at the top of the Brooglie.jl file. 

It may be that the newer version of Julia took out the LinearAlgebra package. 

Cheers,
Kane

**Comment by RedPointyJackson** [comment]
Hello, thanks a lot for the tip! I've added it to the master branch just in case.
